name: Build-Latex

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: A job to Compile Latex file
    steps:
    - uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: dante-ev/latex-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        root_file: 'main.tex'
