name: Build-Latex

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: A job to Compile Latex file
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        root_file: 'main.tex'
        latexmk_shell_escape: true
    - uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: main.pdf
